export enum CardSubTypes {
	COUNCIL = 1,
	GOBLIN = 2,
	LACKEY = 3,
	ALLY = 4,
	COWARD = 5,
	EQUIPMENT = 6,
	THE_HONOURED_ONE = 7,
	SINGLE_USE = 8,
	REUSABLE = 9,
	END_OF_DAY = 10,
	FRIEND = 11,
	FOE = 12,
}