export enum CardSubTypes {
	COUNCIL = 'Council',
	GOBLIN = 'Goblin',
	LACKEY = 'Lackey',
	ALLY = 'Ally',
	COWARD = 'Coward',
	EQUIPMENT = 'Equipment',
	THE_HONOURED_ONE = 'The Honoured One',
	SINGLE_USE = 'Single Use',
	REUSABLE = 'Reusable',
	END_OF_DAY = 'End of Day',
	FRIEND = 'Friend',
	FOE = 'Foe',
	HUMAN = 'Human',
	DEMIGOD = 'Demigod',
	GOD = 'God',
	DINOSAUR = 'Dinosaur',
}