export enum ReminderTexts {
	LEGENDARY_INSTANT = '<i>(You may cast a legendary instant only if you control a legendary creature or planeswalker.)</i>',
	LEGENDARY_SORCERY = '<i>(You may cast a legendary sorcery only if you control a legendary creature or planeswalker.)</i>',
	LEGENDARY_INSTANT_RULINGS = 'You can\'t cast a legendary instant unless you control a legendary creature or a legendary planeswalker. Once you begin to cast a legendary instant, losing control of your legendary creatures and planeswalkers won\'t affect that spell.',
	LEGENDARY_SORCERY_RULINGS = 'You can\'t cast a legendary sorcery unless you control a legendary creature or a legendary planeswalker. Once you begin to cast a legendary sorcery, losing control of your legendary creatures and planeswalkers won\'t affect that spell.',
	PILGRIM_COUNTERS = '<i>(Players with Pilgrim counters have: <i class="ms ms-7 ms-cost ms-shadow"></i>, remove a Pilgrim counter: Exile the top three cards of your library. You may play them this turn without paying their mana costs.)</i>',
	EATING_DRINKING = '<i>(Each instance of putting food in a mouth and each sip count as Eating and Drinking)</i>',
	SPLIT_SECOND = '<i>(As long as this spell is on the stack, players can\'t cast spells or activate abilities that aren\'t mana abilities.)</i>',
	DEVOID = '<i>(This card has no color.)</i>',
	OVERLOAD = '<i>(You may cast this spell for its overload cost.If you do, change its text by replacing all instances of \'target\' with \'each\'.)</i>',
	GOLD_TOKEN = '<i>(A Gold token is an artifact with "Sacrifice this token: Add one mana of any color.")</i>',
	CLEAVE = '<i>(You may cast this spell for its cleave cost. If you do remove the words in square brackets.)</i>',
	GLORY_KICKER = '<i>(You may pay one or more of these additional costs as you cast this spell.You can only pay each cost once.)</i>',
	COMBO_STAR = '<a href="/glossary#Combo_Star">Combo Star</a>',
}